### ISSUE TITLE
assets missing

### ISSUE THREAD

**Issue by AMDmi3** [vladimirgamalian/neopedersia#1]
```
% src/neopedersia 
Error: IMG_LoadTexture failed: Couldn't open assets/tiles/grass.png
```

so it's impossible to check the project out :)

Though, JFYI, it builds fine on FreeBSD.

**Comment by vladimirgamalyan** [comment]
Okay) These ugly assets have been shamelessly added to the git.
Still need to manually set working directory, to resolve required paths.
In my case (mingw) the binary dir looks like:

```
program.exe
assets
    cannon
    machinegun
    ...
```

I'm glad to hear about successful build on FreeBSD!
Thankee!

**Comment by AMDmi3** [comment]
Thanks, now this works fine as well. Is it going to be some kind of tower defence game? Would be nice of you to fill in the readme - I'd like to add this to the [list](https://github.com/AMDmi3/libSDL2pp#users) of projects using SDL2pp, however I don't really have description for it :)
